language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: obscure-gorge-28198
  on:
    repo: davified/ml-ci-cd-demo-express-server
  api_key:
    secure: jKNOYfvQ9IXoSu60FFvEUR6/aSlwnKKQ3+rQ+TlYraVjTH1ivQOhC54vqp1Hzg/fQfNB+IAMhRvi7aAe6sL6NFWuxH9EqkLs7nJmqO8D2vyYpmXFAaqsAyVvG9voYDRagVhl6+S5J1M8XOOEqHF4ZhYFrlNOL549nxcwFN2A97yvmt3ofnHN5f4NUDWIzgY57697HnN6mWBKnbB1hG80QoUom4DAZhZ9DcFieZicDBbRWIUM0V1gl+Izb6AWbQuGCJ7Gu1rdjc9nPgI+IdEiD8Ykh9X7ArEnhZxhmSftWImiRAoEINmkNtb9yvrg21LYm48qp7X+zOQ2mV2RQFY/nbhxzJz6FAxW+1+gtzNI2Lc7Is8XeEiKtymqjIKGeOrlOMQzmUdMJVuQ+IMzTqpYz01OAT3MAB5F05uJENGbqS3F6YN2IQaCh4KwWAMVg1myThZIilgx02cqy3DPYn+f5ERfpDTpF5KOaiNj4H/34NQeynYKb+fVqqaroMkGpE0N2xOHW8Ctohwleq+dXprxn1kEckWGpUJmmVQ4FUSSvXvZFiwAs4ynFNXgceDoBpW/bTPwtfwf4c3vre9garg4DEBnl0rt0Kz9Cf9uwhArB7xWDu77CiXKK3hxskrduvuhHAaqF5Oy7/Uwt+0SgC85V+VRklOT03/H7cSUUBeyf1M=
